from app.models import db, User, Pin, PinComment, environment, SCHEMA
from sqlalchemy.sql import text
import random

comments = [
    "This is such a great idea!",
    "Amazing work, keep it up!",
    "I love this concept!",
    "This is really inspiring.",
    "Fantastic execution!",
    "Very creative!",
    "This is exactly what I needed.",
    "Thanks for sharing!",
    "Great tips, very helpful.",
    "I can't wait to try this.",
    "This looks awesome!",
    "Brilliant!",
    "Such a clever idea!",
    "I'm definitely going to use this.",
    "This is so useful, thank you!",
    "Absolutely love this!",
    "This is incredible!",
    "Great job on this!",
    "Super helpful information.",
    "This is a game changer!",
    "I'm so glad I found this.",
    "This is very informative.",
    "Excellent advice!",
    "This made my day.",
    "Thank you for the inspiration!",
    "I've never thought of it this way before.",
    "This will really come in handy.",
    "I'm impressed with your creativity!",
    "This is perfect for what I'm working on.",
    "I learned something new today!",
    "This is a brilliant solution!",
    "Can't wait to show this to my friends.",
    "You have a talent for this.",
    "This is a fantastic resource.",
    "I appreciate the effort you put into this.",
    "You've inspired me to start my own project.",
    "This has been so helpful, thank you!",
    "Great to see someone doing this.",
    "This is so well done!",
    "I'll definitely be coming back to this.",
    "You've thought of everything!",
    "This is so well explained.",
    "This approach is so unique.",
    "I'm going to implement this ASAP.",
    "This has made a big difference for me.",
    "Such detailed work, amazing!",
    "I love how thorough this is.",
    "This just solved a problem I've had for weeks.",
    "You make it look so easy!",
    "This is exactly what I've been looking for.",
    "Your work never ceases to amaze me.",
    "This is such a great resource.",
    "I can't thank you enough for this.",
    "This saved me a lot of time.",
    "This is pure genius!",
    "I'm so grateful for this.",
    "This is the best I've seen.",
    "Absolutely fantastic!",
    "This is very insightful.",
    "You've really outdone yourself.",
    "This is so inspiring!",
    "This content is gold!",
    "Such an innovative idea!",
    "I'm definitely using this.",
    "This is top-notch work.",
    "You really nailed it!",
    "This is highly recommended.",
    "Such a professional approach.",
    "This is wonderfully done.",
    "Incredibly helpful, thanks!",
    "This is so engaging.",
    "I absolutely needed this.",
    "Such high-quality work!",
    "This is extremely well-done.",
    "This has great potential.",
    "You've got a winner here!",
    "This is so innovative.",
    "Very impressive work!",
    "This is absolutely brilliant.",
    "This stands out from the rest.",
    "This is a huge help.",
    "You've made my day with this.",
    "This is a fantastic find.",
    "I'm thrilled with this.",
    "This is beyond amazing!",
    "This is a game-changer for me.",
    "I can't wait to implement this.",
    "This is a must-see.",
    "Outstanding work!",
    "This is simply the best.",
    "This is truly exceptional.",
    "I'm really impressed by this.",
    "This is a great solution.",
    "This is wonderfully creative.",
    "This is incredibly useful.",
    "You've done a fantastic job.",
    "This is a real eye-opener.",
    "This is just perfect.",
    "Such a helpful post.",
    "This is very well-crafted.",
    "I'm amazed by this.",
    "This is exactly what I was looking for.",
    "I couldn't have done it without this.",
    "This is an excellent resource.",
    "This is top-tier content.",
    "This is very practical advice.",
    "This is incredibly inspiring.",
    "This is such a unique idea.",
    "This is very thoughtfully done.",
    "I really appreciate this.",
    "This is first-class work.",
    "This is extremely helpful.",
    "I'm so glad I found this.",
    "This is a real gem.",
    "This is truly a masterpiece.",
    "This is a superb resource.",
    "This is very enlightening.",
    "This is a true work of art.",
    "This is just what I needed.",
    "This is very well-done.",
    "This is a fantastic example.",
    "This is incredibly detailed.",
    "This is so well-thought-out.",
    "This is incredibly impressive.",
    "This is very insightful.",
    "This is a remarkable piece of work.",
    "This is a fantastic resource."
]

def seed_pin_comments():
    users = User.query.all()
    pins = Pin.query.all()

    for pin in pins:
        for _ in range(random.randint(0, 2)):  # Ensuring about 0 to 2 comments per post
            commenter = random.choice(users)
            comment = PinComment(
                content=random.choice(comments),
                user_id=commenter.id,
                pin_id=pin.id
            )
            db.session.add(comment)
    db.session.commit()

def undo_pin_comments():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.pin_comments RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM pin_comments"))
    db.session.commit()
