from app.models import db, Pin, environment, SCHEMA
from sqlalchemy.sql import text
from faker import Faker
from app.api.AWS import upload_file_to_s3,remove_file_from_s3,get_unique_filename
fake = Faker()

def seed_pins():
    all_pins = [
        # User 1 Pins
        {"user_id": 1, "title": "Top 10 Places to Visit in Europe", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/top10places.jpg", "description": "Explore the must-see destinations in Europe for an unforgettable travel experience. From the romantic streets of Paris to the historic ruins of Rome, discover the best that Europe has to offer with detailed guides and insider tips."},
        {"user_id": 1, "title": "Hidden Gems in South America", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/travel1.webp", "description": "Discover lesser-known yet amazing places in South America. Journey through remote villages, stunning landscapes, and cultural hotspots that are off the beaten path, providing unique experiences away from the usual tourist routes."},
        {"user_id": 1, "title": "Best Homemade Pizza Recipe", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/pizza1.webp", "description": "A step-by-step guide to making delicious homemade pizza. \n1. Prepare the dough: Mix flour, yeast, sugar, salt, water, and olive oil. Knead until smooth and let it rise for 1 hour. \n2. Make the sauce: Combine crushed tomatoes, garlic, olive oil, salt, and basil in a saucepan and simmer for 15 minutes. \n3. Preheat the oven to 475°F. \n4. Roll out the dough on a floured surface and transfer to a baking sheet. \n5. Spread the sauce over the dough, add mozzarella cheese, and your favorite toppings. \n6. Bake for 12-15 minutes until the crust is golden and the cheese is bubbly. \n7. Slice and serve hot."},
        {"user_id": 1, "title": "The Perfect Chocolate Cake Recipe", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/chococake.webp", "description": "Bake a rich and moist chocolate cake with this easy recipe. \n1. Preheat your oven to 350°F and grease two 9-inch round cake pans. \n2. In a bowl, mix 1.5 cups of flour, 1.5 cups of sugar, 3/4 cup of cocoa powder, 1.5 tsp of baking powder, 1.5 tsp of baking soda, and 1 tsp of salt. \n3. Add 2 eggs, 1 cup of milk, 1/2 cup of vegetable oil, and 2 tsp of vanilla extract to the dry ingredients. Beat on medium speed for 2 minutes. \n4. Stir in 1 cup of boiling water (batter will be thin). \n5. Pour the batter evenly into the prepared pans. \n6. Bake for 30-35 minutes or until a toothpick inserted in the center comes out clean. \n7. Cool for 10 minutes, then remove from pans to wire racks to cool completely. \n8. Frost with your favorite chocolate frosting."},
        {"user_id": 1, "title": "Photography Tips for Beginners", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/photography.webp", "description": "Essential tips and tricks to improve your photography skills. From understanding camera settings to mastering composition and lighting, this guide will help you take stunning photos even if you're just starting out."},
        {"user_id": 1, "title": "Editing Photos Like a Pro", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/photoediting.webp", "description": "Advanced photo editing techniques to enhance your images. Learn how to use professional editing software to adjust color, contrast, and clarity, making your photos look like they were taken by a pro."},
        {"user_id": 1, "title": "Summer Fashion Trends 2024", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/summer-fashion.webp", "description": "Stay stylish this summer with the latest fashion trends. From vibrant colors and bold patterns to sustainable materials and innovative designs, keep your wardrobe fresh and fashionable with these top picks."},
        {"user_id": 1, "title": "Winter Wardrobe Essentials", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/winter-essentials.webp", "description": "Must-have clothing items to keep you warm and fashionable in winter. Discover cozy sweaters, chic coats, and stylish accessories that will help you stay comfortable and trendy during the cold months."},
        {"user_id": 1, "title": "DIY Home Decor Projects", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/diy-home-decor.webp", "description": "Transform your space with these easy DIY home decor projects. Learn how to create custom wall art, refurbish old furniture, and craft beautiful home accessories that reflect your personal style."},
        {"user_id": 1, "title": "Minimalist Home Decor Ideas", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/minimilastic-home-decor.webp", "description": "Embrace simplicity with these minimalist home decor ideas. Discover how to create a serene and clutter-free environment by using neutral colors, clean lines, and functional furniture pieces."},
        {"user_id": 1, "title": "Full Body Workout Routine", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/full-body-workout.webp", "description": "A comprehensive workout plan for the entire body. \n1. Warm-up: 5 minutes of jumping jacks and dynamic stretches. \n2. Squats: 3 sets of 15 reps. \n3. Push-ups: 3 sets of 12 reps. \n4. Lunges: 3 sets of 10 reps per leg. \n5. Plank: Hold for 1 minute. \n6. Dumbbell Rows: 3 sets of 12 reps per arm. \n7. Cool down: 5 minutes of stretching."},
        {"user_id": 1, "title": "Home Workout for Beginners", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/home-workout-beginners.webp", "description": "An easy and effective workout routine for beginners at home. \n1. Warm-up: 5 minutes of marching in place and arm circles. \n2. Wall Sit: Hold for 30 seconds. \n3. Knee Push-ups: 3 sets of 10 reps. \n4. Glute Bridges: 3 sets of 15 reps. \n5. Bicycle Crunches: 3 sets of 12 reps per side. \n6. Cool down: 5 minutes of stretching and deep breathing exercises."},
        {"user_id": 1, "title": "Introduction to Python Programming", "link":"https://www.w3schools.com/python/python_intro.asp", "content_url": "https://www.filepicker.io/api/file/93Xqi3aoRZ6HiVsIRRa1", "description": "Learn the basics of Python programming with this introductory guide. Covering fundamental concepts, syntax, and hands-on examples, this guide will help you get started with one of the most popular programming languages."},
        {"user_id": 1, "title": "Advanced JavaScript Concepts","link":"https://developer.mozilla.org/en-US/docs/Web/JavaScript", "content_url": "https://images.yourstory.com/cs/2/96eabe90392211eb93f18319e8c07a74/T4PB-f0c-1686918503273.jpg", "description": "Delve into advanced JavaScript topics and improve your coding skills. Explore higher-order functions, closures, and asynchronous programming with detailed explanations and practical examples."},

        # User 2 Pins
        {"user_id": 2, "title": "Top Beaches to Visit in Asia", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/asia-beach.webp", "description": "Relax and unwind at the most beautiful beaches in Asia. From the pristine sands of Thailand to the crystal-clear waters of the Philippines, discover idyllic beach destinations perfect for your next getaway."},
        {"user_id": 2, "title": "Cultural Tours in Africa", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/africa-tours.webp", "description": "Immerse yourself in the rich culture and history of Africa. Join guided tours that take you through ancient ruins, vibrant markets, and traditional villages to experience the diverse heritage of the continent."},
        {"user_id": 2, "title": "Vegan Dessert Recipes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/vegan-dessert.webp", "description": "Indulge in these delicious and guilt-free vegan desserts. \n1. Vegan Chocolate Mousse: Blend 2 ripe avocados, 1/4 cup of cocoa powder, 1/4 cup of maple syrup, and 1 tsp of vanilla extract until smooth. Chill before serving. \n2. Coconut Milk Ice Cream: Mix 2 cans of coconut milk, 1/2 cup of sugar, and 1 tsp of vanilla extract. Churn in an ice cream maker according to manufacturer’s instructions. \n3. Vegan Banana Bread: Combine 3 mashed bananas, 1/3 cup of melted coconut oil, 1/4 cup of maple syrup, 1 tsp of vanilla extract, 1.5 cups of flour, 1 tsp of baking soda, and 1/4 tsp of salt. Bake at 350°F for 50-60 minutes."},
        {"user_id": 1, "title": "Quick and Easy Breakfast Recipes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/recipe.webp", "description": "Start your day right with these simple and tasty breakfast recipes. \n1. Smoothie Bowl: Blend 1 banana, 1 cup of frozen berries, and 1/2 cup of almond milk until smooth. Pour into a bowl and top with granola, sliced fruit, and a drizzle of honey. \n2. Avocado Toast: Mash 1 ripe avocado with a pinch of salt and pepper. Spread on whole-grain toast and top with a poached egg and a sprinkle of red pepper flakes. \n3. Overnight Oats: Mix 1/2 cup of rolled oats, 1/2 cup of milk, 1/4 cup of yogurt, and 1 tbsp of chia seeds. Refrigerate overnight and top with fresh berries and a drizzle of maple syrup in the morning."},
        {"user_id": 2, "title": "Best Photography Gear in 2024", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/top-photo-gear.webp", "description": "A comprehensive review of the best photography gear for 2024. Explore top cameras, lenses, and accessories that will help you capture stunning photos, whether you're a beginner or a professional."},
        {"user_id": 2, "title": "Top Photography Apps", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/top-photo-apps.webp", "description": "Enhance your photos with these top-rated photography apps. Discover apps for editing, organizing, and sharing your photos, making it easier to create beautiful images on the go."},
        {"user_id": 2, "title": "Street Style Fashion Tips", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/street-style-tips.webp", "description": "Incorporate street style into your wardrobe with these tips. Learn how to mix and match pieces for a casual yet chic look, and stay up-to-date with the latest trends in urban fashion."},
        {"user_id": 2, "title": "Sustainable Fashion Tips", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/sustainable-fashion-tips.webp", "description": "Make eco-friendly fashion choices with these sustainable tips. Find out how to build a stylish wardrobe with ethically made clothing and accessories that are kind to the planet."},
        {"user_id": 4, "title": "Luxury Home Decor on a Budget", "content_url": "https://example.com/home-decor11", "description": "Achieve a luxury look in your home without breaking the bank. Discover budget-friendly decor tips including DIY projects, smart shopping, and strategic styling."},
        {"user_id": 4, "title": "Seasonal Home Decor Ideas", "content_url": "https://example.com/home-decor12", "description": "Refresh your home decor for each season with these ideas. Learn how to use seasonal colors, natural elements, and thematic decorations to keep your space lively and updated."},
        {"user_id": 2, "title": "Yoga Routine for Flexibility", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/yoga-routine.jpg", "description": "Improve your flexibility with this effective yoga routine. \n1. Warm-up: 5 minutes of gentle stretches and deep breathing. \n2. Downward Dog: Hold for 1 minute. \n3. Forward Fold: Hold for 1 minute. \n4. Pigeon Pose: Hold for 1 minute on each side. \n5. Seated Forward Bend: Hold for 1 minute. \n6. Butterfly Pose: Hold for 1 minute. \n7. Cool down: 5 minutes of lying on your back and deep breathing."},
        {"user_id": 2, "title": "HIIT Workout for Beginners", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/hiit-workout-begginer.webp", "description": "A beginner-friendly High-Intensity Interval Training (HIIT) workout. \n1. Warm-up: 5 minutes of jogging in place and dynamic stretches. \n2. Jumping Jacks: 30 seconds, then rest for 30 seconds. \n3. Squat Jumps: 30 seconds, then rest for 30 seconds. \n4. High Knees: 30 seconds, then rest for 30 seconds. \n5. Burpees: 30 seconds, then rest for 30 seconds. \n6. Cool down: 5 minutes of stretching and deep breathing exercises."},
        {"user_id": 2, "title": "Learning HTML and CSS", "link":"https://www.freecodecamp.org/learn/2022/responsive-web-design/","content_url": "https://miro.medium.com/v2/resize:fit:960/1*OlyP02fRFe8pEkJgb6vGTQ.png", "description": "Get started with web development by learning HTML and CSS. This guide covers the basics of creating and styling web pages with hands-on examples and exercises."},
        {"user_id": 2, "title": "Building a Simple Website with React", "link":"https://v2.scrimba.com/learn-react-c0e","content_url": "https://www.edureka.co/blog/wp-content/uploads/2017/08/React-JS-Tutorial_.gif", "description": "Learn how to build a simple and interactive website using React. This guide includes step-by-step instructions, code snippets, and best practices for developing with this popular JavaScript library."},
    
        # User 3 Pins
        {"user_id": 3, "title": "Adventure Travel in New Zealand", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/newZ.webp", "description": "Experience the thrill of adventure travel in New Zealand. From bungee jumping to hiking, explore the best activities and destinations for adrenaline junkies in this beautiful country."},
        {"user_id": 3, "title": "Island Hopping in the Caribbean", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/island-hopping.webp", "description": "Discover the beauty of the Caribbean with an island-hopping adventure. Visit stunning beaches, vibrant towns, and historical sites as you explore multiple islands on your tropical getaway."},
        {"user_id": 3, "title": "Gluten-Free Baking Recipes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/gluten-free-bread.webp", "description": "Enjoy delicious gluten-free baked goods with these recipes. \n1. Gluten-Free Bread: Mix 2 cups of gluten-free flour, 1/4 cup of sugar, 1 tbsp of yeast, 1 tsp of salt, 1 cup of warm water, and 1/4 cup of olive oil. Let the dough rise for 1 hour, then bake at 375°F for 30 minutes. \n2. Gluten-Free Chocolate Chip Cookies: Cream together 1/2 cup of butter and 1/2 cup of sugar. Add 1 egg and 1 tsp of vanilla extract. Mix in 1.5 cups of gluten-free flour, 1/2 tsp of baking soda, and 1 cup of chocolate chips. Drop spoonfuls of dough onto a baking sheet and bake at 350°F for 10-12 minutes. \n3. Gluten-Free Banana Bread: Mash 3 ripe bananas and mix with 1/3 cup of melted butter, 1/2 cup of sugar, 1 beaten egg, 1 tsp of vanilla extract, 1 tsp of baking soda, and 1.5 cups of gluten-free flour. Bake at 350°F for 50-60 minutes."},
        {"user_id": 3, "title": "Homemade Pasta Recipes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/pasta3.webp", "description": "Create delicious homemade pasta dishes with these recipes. \n1. Fresh Egg Pasta: Combine 2 cups of flour and 3 eggs. Knead until smooth, roll out thin, and cut into desired shapes. Cook in boiling water for 2-3 minutes. \n2. Tomato Basil Sauce: Sauté 1 chopped onion and 3 minced garlic cloves in olive oil. Add 4 cups of chopped tomatoes, salt, pepper, and a handful of basil leaves. Simmer for 20 minutes and serve over fresh pasta. \n3. Alfredo Sauce: Melt 1/2 cup of butter in a pan, add 1 cup of heavy cream and 1 cup of grated Parmesan cheese. Stir until smooth and serve over fettuccine."},
        {"user_id": 3, "title": "Creative Photography Techniques", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/photgraph-tech3.webp", "description": "Explore creative photography techniques to enhance your skills. Learn about long exposure, macro photography, and the use of filters to create unique and stunning images."},
        {"user_id": 3, "title": "Portrait Photography Tips", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/photo-portrait.webp", "description": "Improve your portrait photography with these tips. Discover how to use lighting, poses, and backgrounds effectively to capture beautiful and expressive portraits."},
        {"user_id": 3, "title": "Autumn Fashion Trends", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/autumn.webp", "description": "Update your wardrobe with the latest autumn fashion trends. Learn how to layer your outfits, choose the right colors, and accessorize for the fall season."},
        {"user_id": 3, "title": "DIY Fashion Hacks", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/autumn.webp", "description": "Get creative with your fashion by trying these DIY hacks. From customizing your jeans to creating your own jewelry, discover fun and easy projects to personalize your style."},
        {"user_id": 3, "title": "Rustic Home Decor Ideas", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/rustic-decor.webp", "description": "Bring a touch of the countryside into your home with these rustic decor ideas. Use natural materials, vintage furniture, and warm colors to create a cozy and inviting atmosphere."},
        {"user_id": 3, "title": "Small Space Decorating Tips", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/small-space.webp", "description": "Maximize your space with these small space decorating tips. Learn how to use multifunctional furniture, smart storage solutions, and strategic decor to make the most of your compact living area."},
        {"user_id": 3, "title": "Strength Training Routine", "content_url": "https://cdn.shopify.com/s/files/1/1367/5211/products/DSC06295_1.jpg?v=1655381486", "description": "Build muscle and strength with this training routine. \n1. Warm-up: 5 minutes of light cardio and dynamic stretches. \n2. Deadlifts: 3 sets of 10 reps. \n3. Bench Press: 3 sets of 10 reps. \n4. Bent Over Rows: 3 sets of 12 reps. \n5. Shoulder Press: 3 sets of 12 reps. \n6. Cool down: 5 minutes of stretching and foam rolling."},
        {"user_id": 3, "title": "Cardio Workout Plan", "content_url": "https://plus.unsplash.com/premium_photo-1664537980998-a75f424e2b1b?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2FyZGlvfGVufDB8fDB8fHww", "description": "Increase your cardiovascular fitness with this workout plan. \n1. Warm-up: 5 minutes of brisk walking or light jogging. \n2. Running Intervals: 1 minute of sprinting followed by 2 minutes of walking, repeated for 20 minutes. \n3. Jump Rope: 5 minutes. \n4. Cycling: 20 minutes at a moderate pace. \n5. Cool down: 5 minutes of walking and stretching."},
        {"user_id": 3, "title": "Java Programming Basics","link":"https://www.codecademy.com/learn/learn-java", "content_url": "https://static-assets.codecademy.com/assets/course-landing-page/meta/1x1/java-introduction.jpg", "description": "Learn the basics of Java programming with this introductory guide. Understand variables, data types, loops, and basic object-oriented concepts with practical examples."},
        {"user_id": 3, "title": "Data Structures and Algorithms","link":'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/#functional-programming', "content_url": "https://miro.medium.com/v2/resize:fit:1400/1*Dyu63sMUVL-gYEZISOE2BQ.jpeg", "description": "Master data structures and algorithms with this comprehensive guide. Covering arrays, linked lists, stacks, queues, trees, and sorting algorithms, this guide provides detailed explanations and coding examples."},

        # User 4 Pins
        {"user_id": 4, "title": "Historic Sites in Europe", "content_url": "https://example.com/travel7", "description": "Visit the most iconic historic sites in Europe. From ancient ruins to medieval castles, explore the rich history and cultural heritage of this diverse continent."},
        {"user_id": 4, "title": "Exploring National Parks in the USA", "content_url": "https://example.com/travel8", "description": "Discover the natural beauty of the USA by exploring its national parks. Learn about the best hiking trails, camping spots, and breathtaking landscapes that each park has to offer."},
        {"user_id": 4, "title": "Dinner Recipes Under 30 Minutes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/30-min-recipes.webp", "description": "Quick and easy dinner recipes for busy weeknights. \n1. Stir-Fried Vegetables: Heat 1 tbsp of oil in a pan, add 2 cups of mixed vegetables, and stir-fry for 5-7 minutes. Add 2 tbsp of soy sauce and 1 tsp of sesame oil, and cook for another 2 minutes. Serve with rice or noodles. \n2. Chicken Quesadillas: Place a tortilla in a hot skillet, add shredded cooked chicken, cheese, and chopped bell peppers. Top with another tortilla and cook for 2-3 minutes on each side until golden brown and the cheese is melted. \n3. Shrimp Tacos: Cook 1 lb of shrimp with 1 tbsp of taco seasoning. Serve in tortillas with shredded lettuce, diced tomatoes, and a squeeze of lime juice."},
        {"user_id": 4, "title": "Healthy Smoothie Recipes", "content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/healthy-smoothie.webp", "description": "Boost your health with these nutritious smoothie recipes. \n1. Green Smoothie: Blend 1 cup of spinach, 1 banana, 1/2 cup of Greek yogurt, 1/2 cup of orange juice, and 1 tbsp of honey until smooth. \n2. Berry Blast: Blend 1 cup of mixed berries, 1/2 cup of almond milk, 1/4 cup of oats, and 1 tbsp of chia seeds until smooth. \n3. Tropical Delight: Blend 1 cup of pineapple chunks, 1/2 cup of coconut milk, 1/2 cup of mango, and 1 tbsp of flax seeds until smooth."},
        {"user_id": 4, "title": "Landscape Photography Tips", "content_url": "https://example.com/photo7", "description": "Capture stunning landscape photos with these tips. Learn about the best times of day to shoot, how to compose your shots, and techniques for using natural light to enhance your images."},
        {"user_id": 4, "title": "Street Photography Guide", "content_url": "https://example.com/photo8", "description": "Master the art of street photography with this guide. Discover how to capture candid moments, use lighting and shadows, and interact with your surroundings to create compelling street scenes."},
        {"user_id": 4, "title": "Spring Fashion Trends", "content_url": "https://example.com/fashion7", "description": "Stay stylish this spring with the latest fashion trends. Find out what colors, patterns, and fabrics are in season and how to incorporate them into your wardrobe."},
        {"user_id": 4, "title": "Vintage Fashion Inspiration", "content_url": "https://example.com/fashion8", "description": "Get inspired by vintage fashion with these tips and ideas. Learn how to mix and match vintage pieces with modern styles to create unique and timeless looks."},
        {"user_id": 4, "title": "Creative Wall Art Ideas", "content_url": "https://example.com/home-decor5", "description": "Discover creative wall art ideas to add personality to your home. Learn how to create gallery walls, use statement pieces, and incorporate various art styles."},
        {"user_id": 4, "title": "Small Apartment Decorating Hacks", "content_url": "https://example.com/home-decor8", "description": "Maximize your small apartment space with these decorating hacks. Learn how to use multifunctional furniture, vertical storage, and light colors to create an open and airy feel."},
        {"user_id": 4, "title": "Yoga for Beginners", "content_url": "https://example.com/workouts7", "description": "Start your yoga journey with these beginner-friendly poses and tips. Learn how to perform basic yoga poses, improve your flexibility, and build strength with guided routines."},
        {"user_id": 4, "title": "HIIT Workout Routine", "content_url": "https://example.com/workouts8", "description": "seconds of rest, 30 seconds of squat jumps, 30 seconds of rest, 30 seconds of plank, 30 seconds of rest. Repeat the circuit 3 times. \n3. Cool Down: 5 minutes of stretching exercises."},
        {"user_id": 4, "title": "Introduction to Machine Learning","link":"https://www.codecademy.com/learn/paths/machine-learning?g_network=g&g_productchannel=&g_adid=673649958134&g_locinterest=&g_keyword=best%20way%20to%20learn%20machine%20learning&g_acctid=243-039-7011&g_acctid=243-039-7011&g_adtype=&g_adtype=search&g_keywordid=kwd-297562713777&g_ifcreative=&g_campaign=account&g_locphysical=9030014&g_adgroupid=152992285589&g_productid=&g_source=%7Bsourceid%7D&g_merchantid=&g_placement=&g_partition=&g_campaignid=10030170703&g_ifproduct=&utm_id=t_kwd-297562713777%3Aag_152992285589%3Acp_10030170703%3An_g%3Ad_c&utm_source=google&utm_medium=paid-search&utm_term=best%20way%20to%20learn%20machine%20learning&utm_campaign=US_Language%3A_Basic_-_Exact&utm_content=673649958134&gad_source=1&gclid=Cj0KCQjwpNuyBhCuARIsANJqL9MiogXZ6RT8v5e9dxLMhMC8b3j7raCn6gL0HrqavHSv2mUu7SPuA0saAtABEALw_wcB", "content_url": "https://media.geeksforgeeks.org/wp-content/uploads/20230706133033/An-introduction-to-Machine-Learning-01.webp", "description": "Get started with machine learning using Python. Understand the basics of algorithms, model training, and evaluation with practical examples."},
        {"user_id": 4, "title": "Comprehensive Web Development Roadmaps", "link":"https://roadmap.sh/roadmaps","content_url": "https://pinfluence-2024.s3.us-east-2.amazonaws.com/roadmap.jpeg", "description": "Explore comprehensive roadmaps for different web development paths. Detailed guides for Front-End, Back-End, Full-Stack, and DevOps, including essential technologies, tools, frameworks, and best practices for each path to help you plan your learning journey."}

    ]

    create_pins = [Pin(**pin) for pin in all_pins]
    add_users = [db.session.add(pin) for pin in create_pins]
    db.session.commit()
    return create_pins

def undo_pins():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.pins RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM pins"))
    db.session.commit()
